export const GESTURES = {
  NONE: 'NONE',
  FIST: 'FIST',
  INDEX_UP: 'INDEX_UP',
  MIDDLE_UP: 'MIDDLE_UP',
  RING_UP: 'RING_UP',
  PINKY_UP: 'PINKY_UP',
  THUMB_UP: 'THUMB_UP',
  PINCH: 'PINCH',
  MOVE_LEFT: 'MOVE_LEFT',
  MOVE_RIGHT: 'MOVE_RIGHT',
  MOVE_UP: 'MOVE_UP',
  MOVE_DOWN: 'MOVE_DOWN',
  FIST_HOLD: 'FIST_HOLD' // FIST hold 1s
};

